// <auto-generated />
namespace FFGames.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Teams : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Teams));
        
        string IMigrationMetadata.Id
        {
            get { return "201802041303393_Teams"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
